### ISSUE TITLE
Mousing out of the adventure map causes an index out of bounds

### ISSUE THREAD

**Issue by tehdi** [tehdi/farm-adventure#44]
When I mouse out of the bottom of the adventure map while there's an active town tooltip, I get an index out of bounds.

Needs a town at the very bottom of the map - doesn't break for left side, haven't tested top or right.

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FarmAdventure.AdventureForm.MapPanel_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)

**Comment by tehdi** [comment]
I'm not developing the desktop version of Farm Adventure anymore, and the Unity version doesn't have this problem.
